### ISSUE TITLE
Issue Accessing Your Blog on Django SSE PostgreSQL Listen Notify

### ISSUE THREAD

**Issue by Macktireh** [valberg/django-sse#2]
Hello,

I hope this message finds you well. I'm a reader of your blog and recently attempted to access it to revisit your article on Django SSE PostgreSQL Listen Notify. However, I encountered a 404 error indicating that the site is no longer accessible.

I'm wondering if there has been a change in the address for your blog or if the content has been moved to another platform. If so, could you please provide me with the new coordinates so that I can continue benefiting from your valuable content?

Thank you in advance

Best regards,
Macktireh AS

**Comment by valberg** [comment]
Hi @Macktireh 

Thank you for reaching out. I have only recently gotten the time and energy to look at what was up. The blog has been fixed now.
